[package]
name = "open_jtalk"
version = "0.1.7"
edition = "2021"

[dependencies]
open_jtalk-sys = { path = "../open_jtalk-sys", version = "0.1.111" }
thiserror = "1.0.31"

[dev-dependencies]
rstest = "0.12.0"
pretty_assertions = "1.2.1"
